Algoritmo "teste_para_mesa05"
// Disciplina  : ALGORITMOS E LÓGICA DE PROGRAMAÇÃO 2020 - O CURSO COMPLETO
// Professor   : Nelio Alves
// Descrição   : teste de mesa para 05
// Autor(a)    : Artur de Camargo Baldon
// Data atual  : 26/04/2020
Var
// Seção de Declarações das variáveis 

  x, y, i : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   x <- 4
   y <- 0

   para i de x ate 1 passo -1 faca
        y <- y + i
   fimpara
   
   escreval(y)

Fimalgoritmo